[build]
  publish = "build/web"
  command = "chmod +x ./netlify-build.sh && ./netlify-build.sh"

[build.environment]
  FLUTTER_VERSION = "3.19.0" # Replace with your Flutter version if different

# Handle routing for single-page applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200